---

- name: Download awscliv2 installer.
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ aws_cli_version }}.zip"
    dest: "{{ executable_temp_dir | default('/tmp') }}"
    remote_src: yes
    creates: /tmp/aws
    mode: 0755

- name: Run the installer.
  command:
  args:
    cmd: "{{ executable_temp_dir | default('/tmp') }}/aws/install"
    creates: /usr/local/bin/aws
  become: true
  register: aws_install

- name: "Show installer output."
  debug:
    var: aws_install
    verbosity: 2
