- src: azavea.aws-cli
  version: 0.1.0
- src: azavea.docker
  version: 2.0.1
- src: azavea.git
  version: 0.1.0
- src: azavea.pip
  version: 0.2.0
- src: azavea.postgresql
  version: 0.4.0
- src: azavea.postgresql-support
  version: 0.3.1
- src: azavea.postgis
  version: 0.3.0
